[package]
name = "i3pmw-rs"
version = "0.1.0"
authors = ["Rafael Aggeler <r.aggeler@gmx.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
i3ipc = "0.10.1"
